// Medical-emergency detection — a hard, model-independent gate.
// Checked on the caller's raw text BEFORE the turn reaches Gemini
// (core/engine.processTurn): a booking receptionist must never triage.
// On match the engine short-circuits with a scripted 911 redirect, emits an
// `emergency.detected` audit event, and skips tool-calling for that turn.
//
// Matching deliberately over-triggers (fail-safe): a false positive costs
// one scripted sentence; a false negative is a caller in distress getting
// booking small talk.

// Multi-word phrases match as substrings; single words are boundary-checked
// so e.g. "stroke" doesn't fire on "keystrokes".
const EMERGENCY_PHRASES = [
  'chest pain', 'heart attack', 'cardiac arrest',
  "can't breathe", 'cant breathe', 'cannot breathe', 'not breathing',
  'trouble breathing', 'difficulty breathing', 'struggling to breathe',
  'severe bleeding', 'bleeding out', 'bleeding a lot', "won't stop bleeding",
  'passed out', 'losing consciousness',
  'kill myself', 'end my life', 'hurt myself', 'want to die',
  'self harm', 'self-harm',
  'allergic reaction', 'anaphylactic',
  'call 911', 'dial 911', 'call an ambulance', 'need an ambulance',
  'medical emergency', 'this is an emergency', 'having an emergency',
  "it's an emergency", 'its an emergency',
];

const EMERGENCY_WORDS = [
  'stroke', 'seizure', 'seizing', 'overdose', 'overdosed', 'choking',
  'unconscious', 'unresponsive', 'suicide', 'suicidal',
];

const WORD_RES = EMERGENCY_WORDS.map(w => new RegExp(`\\b${w}\\b`, 'i'));

/**
 * Returns the matched phrase/word (generic term, never the caller's text)
 * or null. Same contract as redact.containsHealthHistory.
 */
function containsEmergency(text) {
  if (typeof text !== 'string' || !text) return null;
  const lower = text.toLowerCase();
  for (const phrase of EMERGENCY_PHRASES) {
    if (lower.includes(phrase)) return phrase;
  }
  for (let i = 0; i < WORD_RES.length; i++) {
    if (WORD_RES[i].test(text)) return EMERGENCY_WORDS[i];
  }
  return null;
}

/** Scripted redirect — never generated by the model. */
function emergencyScript(channel) {
  return channel === 'voice'
    ? 'If this is a medical emergency, please hang up now and dial 9 1 1, or go to your nearest emergency room. I am only able to help with lab appointment booking. Goodbye.'
    : 'If this is a medical emergency, please call 911 or go to your nearest emergency room right away. This number can only help with lab appointment booking.';
}

module.exports = { containsEmergency, emergencyScript, EMERGENCY_PHRASES, EMERGENCY_WORDS };
